<?php

namespace Database\Seeders;

use App\Enums\MenuFlag;
use App\Models\HITUAM01\HITUAM_MSHAPPLICATION as Application;
use App\Models\HITUAM01\HITUAM_MSHMENU as Menu;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $applicationHituam = Application::query()->where('VDEPT', 'HITUAM')->first();
        $applicationFactwm = Application::query()->where('VDEPT', 'FACTWM')->first();

        $hituamMenus = [
            [
                'VAPPID' => 'HITUAMF006',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'user-screen',
                'VAPPDESC' => 'Master User Role',
                'VURL' => 'HITUAM/bd/master-userrole',
                'VDESC' => 'Master User Role',
                'NSORTAPP' => 104,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationHituam->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'HITUAMF001',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'brand-appstore',
                'VAPPDESC' => 'Master Application',
                'VURL' => 'HITUAM/bd/master-application',
                'VDESC' => 'Master Application',
                'NSORTAPP' => 101,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationHituam->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'HITUAMF002',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'list',
                'VAPPDESC' => 'Master Menu',
                'VURL' => 'HITUAM/bd/master-menu',
                'VDESC' => 'Master Menu',
                'NSORTAPP' => 102,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationHituam->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'HITUAMF003',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'shield-half',
                'VAPPDESC' => 'Master Service',
                'VURL' => 'HITUAM/bd/master-service',
                'VDESC' => 'Master Service',
                'NSORTAPP' => 103,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationHituam->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'HITUAMF007',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'book',
                'VAPPDESC' => 'Master Role Access',
                'VURL' => 'HITUAM/bd/master-role-access',
                'VDESC' => 'Master Role Access',
                'NSORTAPP' => 106,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationHituam->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'HITUAMF008',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'user-shield',
                'VAPPDESC' => 'Master Role Service',
                'VURL' => 'HITUAM/bd/master-role-service',
                'VDESC' => 'Master Role Service',
                'NSORTAPP' => 105,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationHituam->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
        ];

        $factwmMenus = [
            [
                'VAPPID' => 'FACTWMF001',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'book',
                'VAPPDESC' => 'Configuration',
                'VURL' => 'FACTWM/bd/configuration',
                'VDESC' => 'Configuration',
                'NSORTAPP' => 1,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF002',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'book',
                'VAPPDESC' => 'Master Vendor',
                'VURL' => 'FACTWM/bd/master-vendor',
                'VDESC' => 'Master Vendor',
                'NSORTAPP' => 2,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF003',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'book',
                'VAPPDESC' => 'Data Change Request',
                'VURL' => 'FACTWM/bd/change-request-vendor',
                'VDESC' => 'Data Change Request',
                'NSORTAPP' => 3,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF004',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'book',
                'VAPPDESC' => 'Master News',
                'VURL' => 'FACTWM/bd/master-news',
                'VDESC' => 'Master News',
                'NSORTAPP' => 4,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF005',
                'VFLAG' => MenuFlag::BASIC,
                'VICON' => 'book',
                'VAPPDESC' => 'Master Information',
                'VURL' => 'FACTWM/bd/master-information',
                'VDESC' => 'Master Information',
                'NSORTAPP' => 5,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF006',
                'VFLAG' => MenuFlag::TRANS,
                'VICON' => 'book',
                'VAPPDESC' => 'Good Receipt notes',
                'VURL' => 'FACTWM/ts/good-receipt-notes',
                'VDESC' => 'Good Receipt notes',
                'NSORTAPP' => 1,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF007',
                'VFLAG' => MenuFlag::TRANS,
                'VICON' => 'book',
                'VAPPDESC' => 'Verify PO',
                'VURL' => 'FACTWM/ts/verify-po',
                'VDESC' => 'Verify PO',
                'NSORTAPP' => 2,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF008',
                'VFLAG' => MenuFlag::TRANS,
                'VICON' => 'book',
                'VAPPDESC' => 'Verify non PO',
                'VURL' => 'FACTWM/ts/verify-non-po',
                'VDESC' => 'Verify non PO',
                'NSORTAPP' => 3,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF009',
                'VFLAG' => MenuFlag::TRANS,
                'VICON' => 'book',
                'VAPPDESC' => 'Scan Receipt Invoice',
                'VURL' => 'FACTWM/ts/scan-verify-non-po',
                'VDESC' => 'Scan Receipt Invoice',
                'NSORTAPP' => 4,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF010',
                'VFLAG' => MenuFlag::REPORT,
                'VICON' => 'book',
                'VAPPDESC' => 'GRN Report',
                'VURL' => 'FACTWM/rt/gr-notes',
                'VDESC' => 'GRN Report',
                'NSORTAPP' => 1,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF011',
                'VFLAG' => MenuFlag::REPORT,
                'VICON' => 'book',
                'VAPPDESC' => 'Invoice Report',
                'VURL' => 'FACTWM/rt/invoices',
                'VDESC' => 'Invoice Report',
                'NSORTAPP' => 2,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF012',
                'VFLAG' => MenuFlag::REPORT,
                'VICON' => 'book',
                'VAPPDESC' => 'Report Overview',
                'VURL' => 'FACTWM/rt/overview',
                'VDESC' => 'Report Overview',
                'NSORTAPP' => 3,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF013',
                'VFLAG' => MenuFlag::REPORT,
                'VICON' => 'book',
                'VAPPDESC' => 'Document Managements',
                'VURL' => 'FACTWM/rt/document-managements',
                'VDESC' => 'Document Managements',
                'NSORTAPP' => 4,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
            [
                'VAPPID' => 'FACTWMF014',
                'VFLAG' => MenuFlag::REPORT,
                'VICON' => 'book',
                'VAPPDESC' => 'Login History',
                'VURL' => 'FACTWM/rt/log-histories',
                'VDESC' => 'Login History',
                'NSORTAPP' => 5,
                'VTYPEAPP' => 'LRVL-WEB',
                'NSORTPROJECT' => $applicationFactwm->IID,
                'VCREA' => 'Seeder',
                'DCREA' => now(),
                'DMODI' => null,
            ],
        ];

        Menu::truncate();
        Menu::insert($hituamMenus);
        Menu::insert($factwmMenus);
    }
}
